### ISSUE TITLE
python 3.8 compatibility

### ISSUE THREAD

**Issue by pokulo** [pokulo/errno_converter#2]
# Description

This package is not compatible with Python 3.8 since commit e691d5a510e9bfe2bc1ba6e06550befbdbe14bc3, see e.g.: 
```python
Traceback (most recent call last):
  File "/home/…/.local/bin/http_converter", line 5, in <module>
    from http_converter import main
  File "/home/…/.local/pipx/venvs/errno_converter/lib/python3.8/site-packages/http_converter.py", line 4, in <module>
    from lib.converter import Converter
  File "/home/…/.local/pipx/venvs/errno_converter/lib/python3.8/site-packages/lib/converter.py", line 5, in <module>
    class Converter(object, metaclass=abc.ABCMeta):
  File "/home/…/.local/pipx/venvs/errno_converter/lib/python3.8/site-packages/lib/converter.py", line 26, in Converter
    def get_candidates() -> list[str]:
TypeError: 'type' object is not subscriptable
```

# Affected Version

Commit e691d5a510e9bfe2bc1ba6e06550befbdbe14bc3 changed app version in `pyproject.toml` to `0.1.5`. But git version tags are missing!

# Proposed Solution

This could be solved by using backported typing imports like this one:
```python
from __future__ import annotations
```

**Comment by pokulo** [comment]
python 3.8 ist EOL. so the pyproject.toml might just raise compatibility flag to python 3.9 and later.

**Comment by pokulo** [comment]
Fixed via [a5053fa](https://github.com/pokulo/errno_converter/commit/a5053fac738fe9e91ee0105c8fa88e3b8f47588e) in Version 0.2.0. yet to be released in pypi.
